### ISSUE TITLE
Tweets with Graphic,smileys Create Issue

### ISSUE THREAD

**Issue by bhavikap711** [ezraverheijen/timeline-twitter-feed#1]
No doubts its a great plugin and i have been implementing it on many of my websites.
Off lately, came across an issue where, a tweet having icons/graphics like smiley or trees icons are creating issue. It shows blank area in the below section after the tweet with an icon is fetched. 
http://www.crimson-blue.com/ this is the site where am facing an issue.

**Comment by ezraverheijen** [comment]
Do you still have version 0.9 installed?
Smilies or any other icon should not break the plugin anymore since version 1.0
Please let me know.

**Comment by ezraverheijen** [comment]
This issue should be fixed now with version 1.2.
Please update.
